name = {"English" : {"language":"English",                 "flag":"🇺🇸"},
        "en"	  : {"language":"English",                 "flag":"🇺🇸"},
        "en-GB"	  : {"language":"English (UK)",            "flag":"🇬🇧"},
        "en-AU"	  : {"language":"English (Australian)",    "flag":"🇦🇺"},
        "en-CA"	  : {"language":"English (Canadian)",      "flag":"🇨🇦"},
        "en-IN"	  : {"language":"English (Indian)",        "flag":"🇮🇳"},
        "fr"	  : {"language":"French",                  "flag":"🇫🇷"},
        "French"  : {"language":"French",                  "flag":"🇫🇷"},
        "fr-CA"	  : {"language":"French (Canadian)",       "flag":"🇨🇦"},
        "es"	  : {"language":"Spanish",                 "flag":"🇪🇸"},
        "Spanish" : {"language":"Spanish",                 "flag":"🇪🇸"},
        "es-MX"	  : {"language":"Spanish (Mexico)",        "flag":"🇲🇽"},
        "es_419"  : {"language":"Spanish (Latin America)", "flag":"🇦🇷"},
        "pt"	  : {"language":"Portuguese",              "flag":"🇵🇹"},
        "pt_PT"   : {"language":"Portuguese (Portugal)",   "flag":"🇵🇹"},
        "pt-BR"	  : {"language":"Portuguese (Brazil)",     "flag":"🇧🇷"},
        "it"	  : {"language":"Italian",                 "flag":"🇮🇹"},
        "Italian" : {"language":"Italian",                 "flag":"🇮🇹"},
        "de"	  : {"language":"German",                  "flag":"🇩🇪"},
        "German"  : {"language":"German",                  "flag":"🇩🇪"},
        "zh-Hans" : {"language":"Chinese (Simplified)",    "flag":"🇨🇳"},
        "zh_CN"   : {"language":"Chinese (Simplified)",    "flag":"🇨🇳"},
        "zh-Hant" : {"language":"Chinese (Traditional)",   "flag":"🇭🇰"},
        "zh_TW"   : {"language":"Chinese (Taiwan)",        "flag":"🇹🇼"},
        "zh-HK"	  : {"language":"Chinese (Hong Kong)",     "flag":"🇭🇰"},
        "nl"	  : {"language":"Dutch",                   "flag":"🇳🇱"},
        "Dutch"   : {"language":"Dutch",                   "flag":"🇳🇱"},
        "ja"	  : {"language":"Japanese",                "flag":"🇯🇵"},
        "Japanese": {"language":"Japanese",                "flag":"🇯🇵"},
        "ko"	  : {"language":"Korean",                  "flag":"🇰🇷"},
        "vi"	  : {"language":"Vietnamese",              "flag":"🇻🇳"},
        "ru"	  : {"language":"Russian",                 "flag":"🇷🇺"},
        "sv"	  : {"language":"Swedish",                 "flag":"🇸🇪"},
        "da"	  : {"language":"Danish",                  "flag":"🇩🇰"},
        "fi"	  : {"language":"Finnish",                 "flag":"🇫🇮"},
        "nb"	  : {"language":"Norwegian (Bokmal)",      "flag":"🇳🇴"},
        "no"      : {"language":"Norwegian",               "flag":"🇳🇴"},
        "tr"	  : {"language":"Turkish",                 "flag":"🇹🇷"},
        "el"	  : {"language":"Greek",                   "flag":"🇬🇷"},
        "id"	  : {"language":"Indonesian",              "flag":"🇮🇩"},
        "ms"	  : {"language":"Malay",                   "flag":"🇲🇾"},
        "th"	  : {"language":"Thai",                    "flag":"🇹🇭"},
        "hi"	  : {"language":"Hindi",                   "flag":"🇮🇳"},
        "hu"	  : {"language":"Hungarian",               "flag":"🇭🇺"},
        "pl"	  : {"language":"Polish",                  "flag":"🇵🇱"},
        "cs"	  : {"language":"Czech",                   "flag":"🇨🇿"},
        "sk"	  : {"language":"Slovak",                  "flag":"🇸🇰"},
        "uk"	  : {"language":"Ukrainian",               "flag":"🇺🇦"},
        "hr"	  : {"language":"Croatian",                "flag":"🇭🇷"},
        "ca"	  : {"language":"Catalan",                 "flag":"🇦🇩"},
        "ro"	  : {"language":"Romanian",                "flag":"🇷🇴"},
        "he"	  : {"language":"Hebrew",                  "flag":"🇮🇱"},
        "ar"	  : {"language":"Arabic",                  "flag":"🇦🇪"}}